### ISSUE TITLE
To many decimal places

### ISSUE THREAD

**Issue by WarLord211** [mike-koch/ets2-mobile-route-advisor#103]
I changed the weight to tonns and by some trailers it shows up to 10 decimal Places like:

15,3450000005 t

is there a way to round this to two decimal places?

**Comment by mike-koch** [comment]
Not sure how this issue exists, since GitHub doesn't show it (and 404s when trying to view the link), but waffle.io shows it (and Gitter shows changes).  If you need any assistance with this issue (whoever you are, since I can't see it here :laughing:), please open a new issue.
