### ISSUE TITLE
Map Not appearing at all

### ISSUE THREAD

**Issue by geekmoto13** [mike-koch/ets2-mobile-route-advisor#120]
So I load up both single and multiplayer ets2 and the route advisor is not showing the map at all, even if I let it sit for longer than 5 minutes  skin is version 3.3.0 and the telemetry server is 3.1.0  any ideas on how to force it to show the map or get it to in the first place

**Comment by Koenvh1** [comment]
I'd suggest updating ETS2 Telemetry Server. It should work at version 3.2.4 and above.

**Comment by geekmoto13** [comment]
@Koenvh1 thanks, upgraded to 3.2.5 and that got it working

**Comment by geekmoto13** [comment]
ok got it working by downloading the master fork and using that which is 3.2.5 and its now working
