### ISSUE TITLE
Polish language file invalid

### ISSUE THREAD

**Issue by Koenvh1** [mike-koch/ets2-mobile-route-advisor#125]
Looks like something happened to pl-PL.json, because it isn't a valid JSON file anymore.
(Reported here: http://forum.scssoft.com/viewtopic.php?f=34&t=178742&start=170#p653061 )

**Comment by mike-koch** [comment]
Whoops..... looks like I failed at merging something https://github.com/mike-koch/ets2-mobile-route-advisor/blob/i18n/pl-PL.json#L25-L30

**Comment by mike-koch** [comment]
Fixed.
