### ISSUE TITLE
Map not showing ATS (kind of)

### ISSUE THREAD

**Issue by Malagan** [mike-koch/ets2-mobile-route-advisor#128]
There is a problem with the maps in ATS. It appears that the map is not present but in reallity, if you zoom out enought you will find that you are completly to the west of the USA... Tour truck is now a boat in the middle of the pacific ocean... lol. 

Why? SCS completly rescale the maps in ATS. So all the map files (png) are too small.

Solution, maps have to be recreated for the advisor. :(

Thank you.

**Comment by mike-koch** [comment]
The ATS map hasn't been updated to take account for the rescale, so we need to recapture the map. I can't provide an exact ETA as to when it will be done, but it will be done at some point :wink:

**Comment by Malagan** [comment]
If I can help, let me know. :)

2016-12-21 9:06 GMT-05:00 Mike Koch <notifications@github.com>:

**Comment by Koenvh1** [comment]
Well, the problem currently is that the map is slightly tilted:
![afbeelding](https://cloud.githubusercontent.com/assets/5168825/21468515/61b53816-ca15-11e6-9a5a-4687d0eaad6e.png)

I need to straighten it first, before I can generate a map. The way map capturing works is by systematically creating a lot of screenshots and stitching those together, but that only works when the tiles are straight. The result is something like this:
![afbeelding](https://cloud.githubusercontent.com/assets/5168825/21468522/b4b65860-ca15-11e6-91af-cc4abf56247e.png)

So, if you by any chance know how to make it straight again, let me know 😉

**Comment by Malagan** [comment]
I can correct it using photoshop. Do you think it can works?

2016-12-24 14:16 GMT-05:00 Koen <notifications@github.com>:

**Comment by Koenvh1** [comment]
Well, that's technically possible, but remember that there are roughly 7×20 images that are stitched together, and when an update comes, it starts all over again 😞 
For that reason, I doubt that it is feasible. I have done it before for a small part of the map, but I wouldn't do it for the whole map. I'll keep searching 😉

**Comment by Malagan** [comment]
7*20 = 140. If i'm right, it's just to redo the background straight and
save it. Using Photoshop macros, it should take about 20-30 minutes.

Send me all the pictures you have and i'll try it.

2016-12-26 16:50 GMT-05:00 Koen <notifications@github.com>:

**Comment by mike-koch** [comment]
I'm not sure if rotating the images will do anything or not. Looking at the resulting picture, it appears that the same parts of the map are being recaptured over and over, albeit slightly to the left each time. I wonder how the game tilts the map and if we can tilt it back.

**Comment by Koenvh1** [comment]
Well, ATS switched the projection method for the map in 1.5, causing the map to be slightly tilted. For this reason, our map capturing method no longer works. Capturing a new map is not possible until we have worked around this somehow. 
As to when it is getting fixed: Not anytime soon, if at all. I don't feel like tediously trying to make it work again at the moment, so if you want to search for a solution yourself, go for it. However, if you manage to make the map "untilted" again, I'll recapture it with the proper coordinates and put it in the ETS2 Mobile Route Advisor 😉

**Comment by Koenvh1** [comment]
The map + cities so far: [map_20170119.zip](https://github.com/mike-koch/ets2-mobile-route-advisor/files/775269/map_20170119.zip)

**Comment by fersm** [comment]
Hi. A doubt:

With the image of the map that is in the zip only it would lack to do the process with gdal2tiles and recalculate pointPerPixel and the offset for the version 1.6 of the ATS, right?

**Comment by mike-koch** [comment]
We still need to split the image and tile it because the image is way too big to load in on its own (~20000 x 30000 pixels).

**Comment by fersm** [comment]
Hi. I hope and be of contribution.

By doing a few tests with only the zip information and part of your OL3 code, I think I found a less tedious way to position the image with respect to the cities positions, avoiding the functions of calculatePixelCoordinate, calculatePixelCoordinateEu and game_coord_to_pixels.

This I can georeferencing the image in QGIS with the information of the positions of the cities that is in the file cities_ats_1.5.json, to then generate a raster and finally the tiles.

[https://drive.google.com/open?id=0B1DzrFvAkskDVlJZWVpaQ2FBYlU](url)
[https://drive.google.com/open?id=0B1DzrFvAkskDZVdqeU9GaF9IZDA](url)

If you have the list of cities of the latest version of ATS (1.6), could you pass it to me to do the same process and test with the transformation (png -> raster -> tiles) to corroborate that they match and identify what would be missing ?

With this process in theory would continue to function the same image, avoiding the process of recapture and entails arriving at the complete image.

This week I'm on vacation so I'm almost full time with this :).

I am also seeing how to improve the map capture process, in case this does not work.

I keep working. Greetings.

**Comment by mike-koch** [comment]
I believe the map / cities are the same across ATS 1.5 and 1.6, so zip @Koenvh1 provided above would be the same.  

Any improvements to the mapping process are always welcome, especially since the current process is **very** tedious (which is why I haven't worked on it in a while, to be honest).

**Comment by mike-koch** [comment]
@fersm, any luck with using QGIS with the 1.5 ATS data? I'm quite curious as to how things are going.

**Comment by mike-koch** [comment]
Using the current version of the ATS map with the "player position" image removed.

**Comment by mike-koch** [comment]
Closing this as the mini-map is no longer supported.

**Comment by NarkoLeptik54** [comment]
Salut Mike, voila je viens d'installer route advisor mais je n'est pas la fleche qui indique ou ce trouve le camion. Comment corriger cela ? Merci :)
