### ISSUE TITLE
Speed limit not showing

### ISSUE THREAD

**Issue by blueeagle69** [mike-koch/ets2-mobile-route-advisor#133]
I have the white circle, but no speed limit is showing. I also noticed random losses of the map entirely.
I have one of those infamous split second hiccups while driving and the map disappears on my display. When I get another split second stutter it comes backed. Is the random loss of map due to the latest map dlc?
It's a shame the telemetry sdk doesn't output navigation data. If it did, oh my God!

**Comment by blueeagle69** [comment]
Apologies for the typo. I decided to write the above comment on my phone. Damn that auto correct!

**Comment by Rendername** [comment]
The map itself has not been relevant for a long time due to updates throughout the year. There is an updated version, created on the knee, you can download it here - https://github.com/mike-koch/ets2-mobile-route-advisor/issues/131
As for the disappearance of a fraction of a millisecond - this may be due to faster updates of the data from telemetry. Imho.

**Comment by blueeagle69** [comment]
Hi. Thanks for the reply.
What I meant was, I lose the map and it doesn't come back, until I either
travel to a new area. And sometimes then it comes back.
Hope this makes sense :)

**Comment by Rendername** [comment]
Well, some parts of the map are really missing. So, for example - it's DLC Vive La France, as well as some other road sections that are in the game, but they are not on the router advisor. If it looks more like a bug, maybe a screenshot of the problem does not hurt. :-)

**Comment by blueeagle69** [comment]
No, to be honest, the map disappearing sounds like the dlc and other parts
missing. Because it comes back depending on where I am.
The nav pointer shows. just no map in certain areas.

Thanks.

**Comment by mike-koch** [comment]
@blueeagle69  The speed limit should always be showing if the speed limit sign (either white circle with red border for ETS2 or white square for ATS) is displayed.  If there is no speed limit (such as drop-off/pickup locations), then the entire speed limit sign should disappear until you're back on a road with a speed limit.  Can you provide a screenshot along with the in-game location (I think F11 will give you your coordinates)?  Also your device information would be helpful as well.

And as @Rendername said, some roads are still missing as I haven't updated the maps (and I *still* haven't checked @Rendername 's Vive le France capture yet :frowning_face: ... haven't really had much interest in this lately lol).  To be completely honest, it gets annoying having to do a slow recapture each time the map updates.  I personally would be happy if there was a way to get the in-game GPS image from the telemetry API and display it... but I have no clue on how to do that :laughing:

**Comment by blueeagle69** [comment]
Hi yes I can supply a screenshot later. I have the white circle with red
outline, but nothing shows in that circle no matter where I am on the map.
But the red warning shows up on the current speed display.

**Comment by blueeagle69** [comment]
Right then, apologies, Families!
Anyway, I just popped into ETS2, and realised I was in Brest in France, so no map.
I did a quick teleport to an area outside of France to get the map to display again, and this is what I see.
[IMG]http://i67.tinypic.com/2ugp5s1.jpg[/IMG]

Hope the link works, if not I will re-post.

**Comment by mike-koch** [comment]
Well, I was able to reproduce this **once** when driving from Calais to Paris, so something is going on once in a while. However, I was unable to reproduce it again driving the same exact route.  When it happens again, can you press F12 on your keyboard (in Chrome) to open the developer area and see if there are any errors in the console? If there are any, please post the error here.

**Comment by Rendername** [comment]
I noticed something similar after moving in garage to the city - Felixstowe.
At the same time, there were no errors in the browser console (FF).

Perhaps the cause of this problem is somewhere around here:

```
function game_coord_to_pixels(x, y) {
    // http://forum.scssoft.com/viewtopic.php?p=402836#p402836
    var r = null;
    if (x < -31663 && y < -5618) {
        r = calculatePixelCoordinateUk(x, y);
    } else {
        r = calculatePixelCoordinateEu(x, y);
    }
```
![photo_2017-06-14_17-39-19](https://user-images.githubusercontent.com/7779729/27138132-73499faa-5128-11e7-93cf-48f6bccec118.jpg)
![photo_2017-06-14_17-33-31](https://user-images.githubusercontent.com/7779729/27138133-734be97c-5128-11e7-85f1-33a2e82bd771.jpg)

**Comment by mike-koch** [comment]
What were your exact coordinates at the time? (hitting F11 in game I believe will give your current position)

**Comment by Rendername** [comment]
[-31548 43.2926 -14004](https://user-images.githubusercontent.com/7779729/27139595-1af32804-512c-11e7-8a50-1706b5027379.png)

**Comment by mike-koch** [comment]
Yep, as you suspected. -31548 is larger than -31663, so the skin plots your position based on the EU scale, not UK. That will need to be changed.

**Comment by Rendername** [comment]
Thanks.
Value **31547** [resolved](https://user-images.githubusercontent.com/7779729/27140419-23b9b1fe-512e-11e7-80d9-f9f7239a6638.jpg) this problem in city Felixstowe.
