### ISSUE TITLE
Flexistowe map issue

### ISSUE THREAD

**Issue by BarryCarlyon** [mike-koch/ets2-mobile-route-advisor#135]
So I'm running on branch of the tiles that is a merge of next release france and ATS.

And today drove into Flexistow.
Appraoching from the North, seems a a tile boundary the attached happens.

At tile border suddenly positiining is wrong.

![img_3967](https://user-images.githubusercontent.com/20999/27769893-476e4496-5f2c-11e7-8909-050d0feeba3e.JPG)

**Comment by mike-koch** [comment]
This was also brought up over at #133.  In `map.js` find:

`if (x < -31663 && y < -5618) {`

replace with:

`if (x < -31547 && y < -5618 {`

**Comment by BarryCarlyon** [comment]
Ah yes, I will make the adjustment and test when I visit the area next
