### ISSUE TITLE
GPS Red line 

### ISSUE THREAD

**Issue by TerencePang** [mike-koch/ets2-mobile-route-advisor#136]
Hello. First of all thanks to all contributors! I'm new to here and I find myself tooooooo late to discover I can have the speedometer and map on my iPads. 

But is it possible to show the red line in GPS to guide me to my destination? Thanks!

**Comment by Rendername** [comment]
This is not implemented.

**Comment by Koenvh1** [comment]
The problem is that the game does not provide the necessary information to
implement something like this, so as much as I'd like to, it's currently
not possible.

Op 31 jul. 2017 10:59 a.m. schreef "Dmitriy" <notifications@github.com>:

**Comment by mike-koch** [comment]
As @Rendername and @Koenvh1 have stated, it is not possible to include this information at this time (it most likely never will be unless SCS includes it).
