### ISSUE TITLE
Blue Arrow does not show on map

### ISSUE THREAD

**Issue by tillsmc** [mike-koch/ets2-mobile-route-advisor#141]
Hi there,

I downloaded the mobile-route-advisor and everything is working fine, except that there is no Indicator for my truck (little blue arrow/triangle). 

I have the latest version of all the software needed. Am I doing something wrong or is that a bug?

Thank you for all the work and your support!!! 
Cheers

**Comment by mike-koch** [comment]
I removed the blue arrow from the map as the latest version does not match up perfectly, so the arrow wouldn't be on the actual road.

I'm no longer updating the map, so I don't anticipate this being changed at any point in the near future.
