### ISSUE TITLE
Map not available

### ISSUE THREAD

**Issue by NiekF** [mike-koch/ets2-mobile-route-advisor#142]
The damage and info screens work fine, but it constantly says ''No map available'' in the route tap.  I can't se the map..   Maybe it's because I have map dlc's?  :(

**Comment by mike-koch** [comment]
Are you in ATS or ETS2?

**Comment by NiekF** [comment]
I am in ETS2, sorry for not mentioning that! Thanks for the fast response.

**Comment by mike-koch** [comment]
That text should only appear when using ATS. Have you tried refreshing the page to see if the issue still exists? If you're still having issues, include a full screenshot of the skin as well.

**Comment by NiekF** [comment]
I restarted the server and refreshed the page and android app a few times but it hasn't changed. 
![screenshot_94](https://user-images.githubusercontent.com/31407858/29773127-47dbd7fc-8bfc-11e7-9452-8c5faab5b5f4.png)

**Comment by mike-koch** [comment]
It looks like the skin believes you're running ATS and not ETS2 (based on the truck icon on the tab bar).  Can you provide a dump of the telemetry data? You can get it by going to the second link on the ETS2 Telemetry Server window (it'll look something like `http://localhost:25555/api/ets2/telemetry`)

**Comment by NiekF** [comment]
Here you go.
![screenshot_95](https://user-images.githubusercontent.com/31407858/29773279-f3bbfde0-8bfc-11e7-88da-fea2f3d799d7.png)

**Comment by mike-koch** [comment]
It looks like you may be running an old version of the telemetry server (as you're missing the game.gameName property in the JSON you provided). Download and install the latest version at https://github.com/Funbit/ets2-telemetry-server/archive/3.2.5.zip and then try loading the skin again.

**Comment by NiekF** [comment]
Seems like that was the problem. The map is showing fine now on browser. The app seems to have some trouble loading the map. But it's showing a normal european truck now. Don't where I got the older version of ets telemetry.  Thanks for the quick help! 👍 :)

**Comment by NiekF** [comment]
Now the blue cursor that is supposed to be my truck isn't showing on the map..
The map is moving and following me but I can't see my truck on it.

**Comment by mike-koch** [comment]
From #141:

>I removed the blue arrow from the map as the latest version does not match up perfectly, so the arrow wouldn't be on the actual road.
>
>I'm no longer updating the map, so I don't anticipate this being changed at any point in the near future.

**Comment by Rendername** [comment]
@mike-koch Maybe in the next update return the blue arrow? This is one of the main features in ets2-mobile-route-advisor...
Coming soon DLC of Italy and I will try make re-capture map is more accurate. That blue arrow somewhere may slightly deviate from the road is not very significant, I think. And this is not a significant problem. 🤔

**Comment by mike-koch** [comment]
So long as the map is accurate enough, I'm more than willing to re-add the blue arrow

**Comment by RealTrueDeviL** [comment]
I also have this 'no map available' issue, I take it, it don't work as advertised, as in, it don't work for ATS, as the ats map folder only has the .json file, and nothing else, even tho it's advetised as "ETS2 / ATS Mobile Route Advisor".. When will the ATS part be added?

**Comment by Koenvh1** [comment]
@RealTrueDeviL See https://github.com/mike-koch/ets2-mobile-route-advisor/issues/144 
So, if you feel like taking on the challenge, go for it 😉

**Comment by RealTrueDeviL** [comment]
> @Koenvh1 If I knew how to, maybe I would 😛

**Comment by Koenvh1** [comment]
https://github.com/Koenvh1/ETS2-City-Coordinate-Retriever/blob/master/Capturing%20maps.md

There you go. You will need to update the mod for the latest version of ATS, as well as skew the map.
It isn't easy, I can't give you a step-for-step guide, because it changes every version. (That's also what makes it so difficult and tedious)

**Comment by RealTrueDeviL** [comment]
@Koenvh1 Holy crap, that looks a lot of work, I didn't expect it to be easy, but damn, I see why there isn't an ATS map, however, it shouldn't have it in the title either.. Not complaining, just pointing it out 😝

**Comment by Koenvh1** [comment]
The Route Advisor screen in ATS/ETS2 is more than just the map. It also shows the statistics for the truck and the delivery, and that still works in ATS

**Comment by mike-koch** [comment]
*Everything else* in the skin works for ATS, so why shouldn't it be in the title? It's just the map that isn't there.

**Comment by RealTrueDeviL** [comment]
@mike-koch I suppose, it's just a little misleading, is all

**Comment by Rendername** [comment]
I re-did capture map with all the additions DLC of ATS. However, the complexity of its positioning in ets2-mobile-route-advisor\maps\ats\js\map.js Someone can help with that? I would like to understand how to calculate the parameters on function  calculatePixelCoordinate and after completion of the work, make a Pull Request. Size map 13788 x 10210px.

**Comment by Koenvh1** [comment]
It used to be `((coordinates2 - coordinates1) / (pixels2 - pixels1)) / 2`
Example used for ATS: Redding crossing: Pixels: X: 2244 Y:1278 Ingame coordinates: X: -61235.7 Y: 2328.74
San Francisco crossing: Pixels: X: 2250 Y: 3666 Ingame coordinates: X: -61215.9 Y: 13385.4
((13385.4 - 2328.74) / (3666 - 1278)) / 2

**Comment by Rendername** [comment]
Example city **Kingman.**
Kingman in image:  X: 7588 Y: 6020
Kingman in game:   X: -82131 Y: 13060

((13060 - (-82131)) / (6020 - 7588)) / 2

95191  /  -1568  /  2  =  -30,35427295918367

Is it wrong?

```
function calculatePixelCoordinate(x, y, pointsPerPixel, x0, y0) {
    return [
        (x / pointsPerPixel + x0) | 0,
        (y / pointsPerPixel + y0) | 0
    ];
}
function calculatePixelCoordinateEu(x, y) {
    return calculatePixelCoordinate(x, y, -30,35427295918367, 95191, -1568); //x+16, y+4
}

```
![kingman_ps](https://user-images.githubusercontent.com/7779729/34098145-80b1f596-e3ec-11e7-945a-fab6d7900f30.png)
![kingman_ats](https://user-images.githubusercontent.com/7779729/34098144-80907f9c-e3ec-11e7-93e8-7f6e0f596c7d.png)

**Comment by mike-koch** [comment]
You'll want to use 2 different (x,y) coordinate pairs to get your scale.  So, if you have:
  - Kingman at (w1, x1) in-game coordinates and (y1, z1) pixels
  - San Francisco at (w2, x2) in-game coordinates and (y2, z2) pixels

Then you would use (x2 - x1) / (z2 - z1) / 2 to get your scale. You won't get a proper scale with only 1 data point.

**Comment by Rendername** [comment]
Maybe after SCS stretched map in ATS, so this function is not suitable, since I didn't get true result. If someone can help to choose the appropriate value in a function would be very grateful. The current version cities.js (+new mexico cities) and image map itself via the link in the message...

[cities.txt](https://github.com/mike-koch/ets2-mobile-route-advisor/files/1573014/cities.txt)
[map.png](https://user-images.githubusercontent.com/7779729/34175404-6252d940-e50d-11e7-8621-c3ac079769da.png)
