### ISSUE TITLE
ATS - No map available

### ISSUE THREAD

**Issue by zorial** [mike-koch/ets2-mobile-route-advisor#144]
Hey!
Is it possible to display maps in ATS version 3.3.3? I have a No map available message.
Telemetry Server version - 3.2.5

![screenshot_2017-09-09-03-17-33](https://user-images.githubusercontent.com/19171690/30235815-da9f7cd2-950d-11e7-9394-df8f208d3803.png)

**Comment by Rendername** [comment]
https://github.com/mike-koch/ets2-mobile-route-advisor/issues/128#issuecomment-325337116

**Comment by mike-koch** [comment]
Per the release notes:

>- Disabled ATS map (see below for more information)
>
>NOTICE: Due to the amount of time needed to re-build the map after each DLC release, and how complex the process is, the map section of the route advisor will no longer be updated unless someone can find a simple way to update the map.
