### ISSUE TITLE
Only seeing a big O

### ISSUE THREAD

**Issue by tcBorek2002** [mike-koch/ets2-mobile-route-advisor#149]
Hey,
When I use the mobile route advisor I just get to see this. 
![afbeelding](https://user-images.githubusercontent.com/33029446/31891985-2f98fa48-b808-11e7-9b02-32b51210b3fb.png)
This is my crahs dump: 
![afbeelding](https://user-images.githubusercontent.com/33029446/31892053-5b08d6a8-b808-11e7-9a9c-a31da56c8982.png)
I get it while using ets2mp.
Can you help me?
Borek

**Comment by mike-koch** [comment]
The "big O" is a message box that will show certain messages depending on the state of the game (such as "Connected, waiting for the drive...").  Anyways, I'm guessing there's some sort of JavaScript error that is occurring on the skin.  Are there any errors in the JavaScript console? (press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd> to open the console in Firefox)

**Comment by tcBorek2002** [comment]
Thanks for the really fast answer. This is what I get: 
![afbeelding](https://user-images.githubusercontent.com/33029446/31892809-360f4e3e-b80a-11e7-9c9e-05b283f6149e.png)
Btw I have the problem to on my Ipad.

**Comment by Rendername** [comment]
In another browser the same problem? 
Maybe can browser extensions affect this behavior

**Comment by tcBorek2002** [comment]
I have this problem with every browser on my pc and with every browser on my Ipad. I did see it said : "Connected, waiting for the drive..." before I started the game.

**Comment by mike-koch** [comment]
I'm going to go ahead and close this since it has been inactive for about 3 months. If you continue to have an issue, feel free to open a new issue.
