### ISSUE TITLE
Indicate When The User is in a Special Transport Delivery

### ISSUE THREAD

**Issue by mike-koch** [mike-koch/ets2-mobile-route-advisor#152]
It would make for some nice eye candy (😍) to "skin" the route advisor during a special transport mission.  We'd have to have a list of cargo IDs that pertain to special transport and then compare the current cargo with the list to see if there is a match.

**Comment by Rendername** [comment]
The cargos IDs  in the attachment. What refers to skin, can make for some condition, if cargo special transport, to apply the following styles to css:
![skin](https://user-images.githubusercontent.com/7779729/35777691-57362d20-09c3-11e8-818f-0de66d64cf09.png)


> .dashboard > aside {
> 	background: repeating-linear-gradient(-65deg, #111111, #2c2c2c 35px, #DBA901 35px, #DBA901 70px);
> }
> 
> .dashboard > nav {
> 	background: repeating-linear-gradient(-65deg, #2c2c2c, #2c2c2c 35px, #DBA901 35px, #DBA901 70px);
> }


[cargos_IDs.txt](https://github.com/mike-koch/ets2-mobile-route-advisor/files/1692764/cargos_IDs.txt)
[cargos_RU-ru.txt](https://github.com/mike-koch/ets2-mobile-route-advisor/files/1692765/cargos_RU-ru.txt)
