### ISSUE TITLE
Route Advisor edit

### ISSUE THREAD

**Issue by Klaax** [mike-koch/ets2-mobile-route-advisor#158]
Hello, can I publish my version of this telemetry skin.? It's edited to show other things, map is removed, etc..(I can send pics of it). I just need your permission :smiley:

PS: This is the only way I can contact you (you can pm me on forum.scssoft.com, username: Klaax)

**Comment by mike-koch** [comment]
This project is licensed under the MIT License, so you are free to modify and publish it 🙂
