### ISSUE TITLE
Add Current Navigation Route

### ISSUE THREAD

**Issue by HUM24H** [mike-koch/ets2-mobile-route-advisor#174]
Hi,

Would it be possible to add the current navigation route (Red route line) that shows up on the in game Sat Nav system?

This would be an immensely helpful feature to add as that way it would complete the skin and make it a very versatile addition to a sim setup.

If this has already been suggested or is in the works then apologies for the duplicate.

Regards,

Humzah

**Comment by meatlayer** [comment]
As far as I know, the telemetry server does not return such data regarding GPS points on the map, so it is hardly possible to implement this.

**Comment by mike-koch** [comment]
Dmitriy is correct.  It is currently not possible to pull turn-by-turn information from the telemetry SDK.
