### ISSUE TITLE
Use Layers for POIs

### ISSUE THREAD

**Issue by mike-koch** [mike-koch/ets2-mobile-route-advisor#48]
Instead of having fuel markers (and other POIs) directly embedded into the image tiles, we should use layers instead.  A list of POIs can be found at https://gist.github.com/mike-koch/bdadae22eb616b4b9dfb. These POIs include:

(Checkboxes are for default ETS2 map only)
- [x] Cities
- [ ] Businesses
- [ ] Fuel
- [ ] Service
- [ ] Garage
- [ ] Dealer
- [ ] Highway/motorway numbers (country and number)
- [ ] Speed camera locations
- [ ] Hotel
- [ ] Parking
- [ ] Toll booths
- [ ] Quarries

Items that are not in the POIs, but would be nice:
- [ ] Ferries
- [ ] Train Tunnels (there might be a more specific, better name that that :stuck_out_tongue: 

It would be nice to have each layer separate, allowing users to toggle the layers they want to see on the map. Also these layers should never rotate, so they are always the correct orientation when viewing the map, regardless of the map's rotation.

Roads images might be able to be pulled via: `http://ets2map.com/mapicons/Roads/<road-name>`

**Comment by Koenvh1** [comment]
The gist URL returns a 404

**Comment by mike-koch** [comment]
Fixed :smile: I changed my username a few months ago and didn't update the gist url.

**Comment by mike-koch** [comment]
Closing as I'm retiring map capturing for the foreseeable future.
