### ISSUE TITLE
Voice Alerts / Prompts

### ISSUE THREAD

**Issue by mike-koch** [mike-koch/ets2-mobile-route-advisor#63]
A few people on the SCS forums have asked if there would be voice prompt support in areas... not exactly sure what prompts they would like though.  Maybe some of these?
- Over speed limit
- Approaching destination

Perhaps if we utilize the list of POIs we can have triggers for arriving to tolls, etc. I don't think tolls are in the list I found, though.

**Comment by Koenvh1** [comment]
As of 1.23, the current speed turns red when speeding. Might be worth adding in a similar fashion

**Comment by mike-koch** [comment]
That's a nice addition. Is there a threshold before it goes red (such as 5 km/h (or mph)), or is it instant?

**Comment by Koenvh1** [comment]
Not sure, as I haven't tested the new version yet. From what I have heard it gradually becomes redder. 

If you were to set a treshold, set it at  >3km/h. Going 53km/h past a 50km/h won't get you fined, going 54km/h will. (Guess where most my speeding tickets come from :laughing: )

**Comment by Koenvh1** [comment]
A screenshot that I just received:
http://images.akamai.steamusercontent.com/ugc/475500450712510524/429A344B9CD6CA50F6F565BFC3F8AD124CC29244/

**Comment by denilsonsa** [comment]
Idea on how to implement that in a gradual way: change the gradient from "dark gray → light gray → dark gray" to "semi-transparent black → transparent → semi-transparent black".

That way, we can easily change a single background color to red and the gradient will adapt smoothly. For instance, at max-speed, the color will still be gray, and at around 7% (What's the correct value? Is it a percentage or an absolute value?) above the max-speed, the color will be red. In between, the color will change gradually.

**Comment by Koenvh1** [comment]
It is absolute. >3km/h. will get you fined.

I thought about creating a transparent layer on top of it, and gradually making it more opaque. It will have the same effect either way.

**Comment by mike-koch** [comment]
According to Max on the SCS forums, there is a threshold value that is calculated for ATS.  It is 10% or 5mph, whichever is **higher**.  http://forum.scssoft.com/viewtopic.php?f=178&t=202362&p=523943#p523943.  It's possible that ETS2 is absolute, not sure though. I'll have to jump in-game and see how the route advisor acts when I start speeding :grinning:

**Comment by mike-koch** [comment]
For ATS, the the speed starts turning red at 1 mph over, and then goes to bright red at 5 mph, and says at that same red from that point forward. (So in terms of transparency, it could be 20% visible at 1mph over, 40% visible at 2mph over, etc).  Not sure about ETS2 tho since I'm not opted into the public beta.
