### ISSUE TITLE
ProMods/RusMap Support

### ISSUE THREAD

**Issue by mike-koch** [mike-koch/ets2-mobile-route-advisor#90]
*Related to #85*

The `promods-support` branch holds the necessary map tiles and such for Promods and RusMap support.  Everything is working, however a few things need to be done:

- [x] Look into hiding some labels at certain zoom levels. Right now, everything looks awfully congested when zoomed out.
- [x] Add **Brest (FR)**. Both `goto brect` and `goto brest` went to the same place. The map editor might be necessary to find the location of **Brest (FR)**
- [x] Bordeaux (FR). The teleporter goes to Bor (CZ), cannot find it and chooses Bordeaux.
- [x] San Sebastian/Donestia (ES). For some reason, it chooses Douglas over San Sebastian/Donestia.
- [x] Haparanda (S). It also has Aranda de Duero as a value.
- [x] Turku (FI). It also has Ulm.
- [x] Timisoara (RO). It is missing.
- [x] All countries from Going East are missing too (Whoops, my bad)
- [x] Convert this into a map pack

**Comment by Koenvh1** [comment]
Easiest way to find Brest (FR) is to temporarily disable RusMap.

**Comment by denilsonsa** [comment]
I could describe here in this comment what I did, but that would spoil the surprise. ;)

Just look at the [live demo](http://denilsonsa.github.io/ets2-stuff/openlayers-koenvh1.html), and/or look at [the commit](https://github.com/denilsonsa/ets2-stuff/commit/a6bd624d08dd4264a5f094ffa0f57de1c309ced7). I think you will like it, and one checkbox from this issue might be solved.

**Comment by Koenvh1** [comment]
Sorry, the surprise was already spoiled because my email showed the commit first :stuck_out_tongue: 

Looks great! 

Once again I found a few problems... I've compiled [a list](https://github.com/Koenvh1/ETS2-City-Coordinate-Retriever/blob/master/cities_conflicts.txt) of them (in case I find more). I'll edit the converter to make it detect those discrepancies and let the user choose the correct city.

**Comment by Koenvh1** [comment]
I've added the cities from Going East: https://github.com/Koenvh1/ETS2-City-Coordinate-Retriever/blob/master/cities_east.json

**Comment by Koenvh1** [comment]
Most map issues have been fixed:
https://github.com/Koenvh1/ets2-stuff/blob/master/cities-promods-rusmap.js

I do not have Brest (FR) yet, and I did not alter the zoom level values.

**Comment by mike-koch** [comment]
Brest (FR) is at -58195.46, 7.11, 3848.58 according to the map editor. (sharing this here so I don't forget what it is when I update the city list :smiley: )

**Comment by mike-koch** [comment]
Everything here is good to go AFAIK. Closing.
