### ISSUE TITLE
New map image for the default ETS2 map

### ISSUE THREAD

**Issue by Koenvh1** [mike-koch/ets2-mobile-route-advisor#91]
As there currently is a way to add the city names as layers to the map, perhaps it would be worth it to do the same for the default map in ETS2. I have adjusted @Funbit 's map to be more in line with the original map for ETS2.

What does this mean?
Dark-grey background, orange roads. No country names, city names or borders. This way it should be less distracting to use.

A download link: http://www.mediafire.com/view/lj0bvz95wbti737/map-funbit-edited.png 
Please be aware that this is a large image, so it may consume quite some memory.

**Comment by mike-koch** [comment]
Closing this as #92 was merged in which contains the new default map.
