### ISSUE TITLE
Add GPS Support to ATS

### ISSUE THREAD

**Issue by iTsFILIPOficial** [mike-koch/ets2-mobile-route-advisor#95]
Hey not sure how much work it is but would it be possible to add GPS support to ATS?

**Comment by Koenvh1** [comment]
Well, the main problem currently is that we need to capture the map. In order to do that, we need a solid colour background, and not the garage that you'll normally see as the menu's background.

**Comment by iTsFILIPOficial** [comment]
@Koenvh1 Is there a way to change the background? Or is that now yet done in ATS

**Comment by Koenvh1** [comment]
There is, but it requires editing the model. I've not managed to do that yet.

**Comment by Koenvh1** [comment]
Good news! We're working on a map for ATS.
http://www.mediafire.com/view/ovg51f0c5vzf7h9/map.png
