### ISSUE TITLE
Map disappears when in reach of city name

### ISSUE THREAD

**Issue by Koenvh1** [mike-koch/ets2-mobile-route-advisor#98]
So, I tested my map, and I found a little problem.

Once a city name gets into view, the map disappears. 
The problem lies in the createTextStyle function (can be tested by commenting out `feature.setStyle(createTextStyle);`)

This happens with the ETS2 Telemetry Server app for Android (5.0.1). Huawei P8 Lite. (Not on Firefox or Chrome). The map only disappears when using "point in vehicle's direction". When having north at the top, it doesn't malfunction (but the cities still aren't shown)
(Also, it seems like the map doesn't disappear with OpenLayers 3.9, but it does with 3.14.2)

**Comment by mike-koch** [comment]
I did some testing on an Asus Nexus 7 (2012) and LG Optimus L90 both running CM13, and I had no issues.  The server app is nothing more than a thin wrapper over the webpage itself, so I just went to the URL in Chrome and added it to my home screen :laughing: . It works exactly like the app, but runs on the Chrome engine instead of whatever the app uses.

**Comment by Koenvh1** [comment]
Yes, but that way, the top notification bar is still visible. Also, won't my phone's screen go out after not using it? (Note: Yes it did while writing this message)

The app uses WebView, so that's not ideal. Funny thing is that the player icon does show without a problem.

**Comment by mike-koch** [comment]
I wonder if it's worth it to utilize https://github.com/mogoweb/chromium_webview to use a Chromium-based WebView, thus resulting in uniformity among devices.

**Comment by Koenvh1** [comment]
Well, an upgrade to Android 6.0 fixed it. It is probably a phone/webview specific issue, and therefore I do not think it is necessary to "fix" something that is not broken.
